name: Run tests

on:
  pull_request:
    branches:
      - ci

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Dependencies
      run: npm ci

    - name: Run e2e
      run: npm e2e

    - name: Run test-ci
      run: npm run test-ci