name: Project setup
description: Setup node and project dependencies

runs:
  using: "composite"
  steps:
    - name: Setup node 
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: npm
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Build project
      run: npm run build
      shell: bash
