env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - standard-with-typescript
  - react-app
  - react-app/jest
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.json
settings:
  import/extensions:
    - .js
    - .jsx
    - .ts
    - .tsx
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
plugins:
  - react
rules: {
  import/prefer-default-export: 0,
  no-console: 0,
  react/prop-types: "off",
  react/react-in-jsx-scope: 0,
  "@typescript-eslint/semi": "off",
  "@typescript-eslint/quotes": "off",
  "@typescript-eslint/comma-dangle": "off",
  "@typescript-eslint/explicit-function-return-type": "off",
  testing-library/prefer-screen-queries: "off",
  testing-library/no-debugging-utils: "off",
  "@typescript-eslint/no-unused-vars": "off"
}
