name: Project setup

env:
  node-version: 18.x

runs:
  using: "composite"
  steps:
    - name: Setup node ${{ env.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
