name: autotests-action
on: [pull_request, workflow_dispatch]
jobs:
    unit-tests:
        runs-on: ubuntu-22.04

        steps:
            - name: Get source code
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: node_modules_cache-${{ hashFiles('**/package-lock.json') }}

            - name: Install other dependencies
              run: npm ci

            - name: Run unit tests
              run: npm run test-ci

    e2e-tests:
        runs-on: ubuntu-22.04

        steps:
            - name: Get source code
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: node_modules_cache-${{ hashFiles('**/package-lock.json') }}

            - name: Install other dependencies
              run: npm ci

            - name: Install playwright
              run: npx playwright install

            - name: Run e2e tests
              run: npm run e2e-ci
