name: Autotests on Pull Request

on: [pull_request]

jobs:
  autotests:
    name: Autotests for Pull Requests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run autotests
        run: npm run test-ci
