name: CI testing 

# on simple pull requests and pushes just run the tests
on:
  push:
    branches: [ master ]
    tags-ignore:
      - '**'
  pull_request:
    types: [ opened, reopened ]
    branches: [ master ]
    tags-ignore:
      - '**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
        with:
          fetch-depth: 0
    - name: Run tests from reusable workflow
      uses: ./.github/actions/checks
