# it is a reusable part of code, because it is needed for releases and commits

name: Tests

on:
  workflow_call:
    inputs:
      save-artifacts:
        required: false
        default: false
        type: boolean

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: npm run test-ci
      
      - name: Save test results to artifacts
        uses: actions/upload-artifact@v3
        if: ${{ inputs.save-artifacts }}
        with:
          name: unit-test-report
          path: test-report.html
          retention-days: 10

  playwright-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install browsers and dependencies for playwright
        run: npx playwright install --with-deps chromium
      
      - name: Build the app
        run: npm run build
      
      - name: Run e2e tests
        run: npm run e2e-ci
        env:
          CI: true
      
      - name: Save test results to artifacts
        uses: actions/upload-artifact@v3
        if: ${{ inputs.save-artifacts }}
        with:
          name: playwright-test-report
          path: playwright-report/
          retention-days: 10
  
  lint-commits-push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install @commitlint/cli @commitlint/config-conventional
      
      - name: Lint the commits
        run: npx commitlint --from HEAD~1 --verbose
  
  lint-commits-pull-request:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install @commitlint/cli @commitlint/config-conventional
      
      - name: Lint the commits
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
