name: CI - Deploy

on:
  push:
    tags:
      - v[0-9]+

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: npm run test-ci
      
      - name: Save test results to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-report
          path: test-report.html
          retention-days: 10

  playwright-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install browsers and dependencies for playwright
        run: npx playwright install --with-deps chromium
      
      - name: Build the app
        run: npm run build
      
      - name: Run e2e tests
        run: npm run e2e-ci
        env:
          CI: true
      
      - name: Save test results to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: playwright-test-report
          path: playwright-report/
          retention-days: 10
  
  lint-commits-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install @commitlint/cli @commitlint/config-conventional
      
      - name: Lint the commits
        run: npx commitlint --from HEAD~1 --verbose

  release:
    runs-on: ubuntu-latest
    needs: [unit-test, lint-commits-push, playwright-e2e-tests]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: previousTag
        run: |
          name=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | tail -2 | head -1)
          echo "previousTag: $name"
          echo "previousTag=$name" >> $GITHUB_ENV

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ env.previousTag }}
          includeInvalidCommits: true # to add the full referencing of conventional commits (e.g. ci: is skipped by the action)
          writeToFile: false # just add the references in the release

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true # allow to update already existing release
          draft: false # automatically resolve
          makeLatest: true
          name: "RELEASE: ${{ github.ref_name }} on ${{ env.NOW }}"
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }} 
          artifacts: "playwright-test-report,unit-test-report" # add the test results

  publish:
    runs-on: ubuntu-latest
    needs: [unit-test, lint-commits-push, playwright-e2e-tests]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build the app
        run: npm run build
      
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}