on:
  issues:
    types: [opened]
jobs:
  test-workflow:
    uses: ./.github/workflows/pr-test.yaml
  build-and-deploy:
    needs: test-workflow
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm ci
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
  titlePrefixCheck:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          comment: |
            Tests passed and build successfully uploaded to gh-pages
