name: Deploy on GP
on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-job:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Get the repo code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build
