name: Lint commits

on: [push, pull_request]

jobs:
  commitLint:
    runs-on: ubuntu-latest
    steps:
    
      - name: Get sourcecode
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          npm ci
          npm install -g @commitlint/cli @commitlint/config-conventional
          echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js
          
      - name: Validate current commit
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose
        
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
          
      
