name: Lint Commit Messages
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/*'


jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
  lint:
    runs-on: ubuntu-latest
    needs: commitlint
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Linting code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Unit testing
        run: npm run test-ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: E2e testing
        run: npm run e2e-ci
