name: Lint-Commit
on: [push]

jobs:
  commitlint:
    name: lint-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
