name: test PR
on:
  pull_request:
    branches:
      - master
env:
  CI: true
  JEST_JUNIT_OUTPUT_DIR: test-results
jobs:
  build:
    name: test-check
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
      - run: npm ci
      - run: npm run test-ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: xvfb-run --auto-servernum -- npm run e2e-ci
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.xml