name: Run Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps chromium

      - name: Run tests
        run: npm run test && npm run e2e

      - name: Set test status
        uses: actions/github-script@v4
        with:
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            const { data: checks } = await github.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pullRequest.head.sha
            });

            const hasFailingChecks = checks.check_runs.some(check => check.conclusion === 'failure');

            const status = hasFailingChecks ? 'failure' : 'success';

            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: pullRequest.head.sha,
              state: status,
              target_url: checks.html_url,
              context: 'Run Tests'
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
