name: Run Tests

on: [pull_request, workflow_call]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps chromium

      - name: Run tests
        run: npm run test && npm run e2e

