name: Pull requst
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited,reopened]
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Echo event
        run: echo ${{toJSON(github.event)}}