name: CI

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Deps
      run: npm ci
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx

  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} 
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Deps
      run: npm ci
    - name: Run Unit Tests
      run: npm test
    - name: Run e2e
      run: npx playwright install && npm run e2e
