name: Pull-Request-Verification
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types: [opened, edited, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  testing-job:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Get the repo code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps chromium

      - name: "Tests: unit"
        run: npm run test-unit-ci

      - name: "Tests: e2e"
        run: npm run test-e2e-ci

      - name: Upload Artifacts (unit tests)
        uses: actions/upload-artifact@v3
        with:
          name: Report (unit tests)
          path: test-report.html
          if-no-files-found: error

      - name: Upload Artifacts (e2e tests)
        uses: actions/upload-artifact@v3
        with:
          name: Report (e2e tests)
          path: ./playwright-report
          if-no-files-found: error

      - name: Echo finish
        run: echo 'Testing-job is done'
