name: CI pipeline testing
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: npm run test-ci
  
  playwright-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install browsers and dependencies for playwright
        run: npx playwright install --with-deps chromium
      
      - name: Build the app
        run: npm run build
      
      - name: Run e2e tests
        run: npm run e2e-ci
        env:
          CI: true
  
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install @commitlint/cli @commitlint/config-conventional
      
      - name: Lint the commits
        run: npx commitlint --from HEAD~1 --verbose
