name: Release

on:
  push:
    tags:
      - 'v[0-9]+'

jobs:
  release:
    permissions: write-all

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Generate Tag Report
        run: bash ./.github/scripts/generate_report.sh 
      - name: Create issue
        uses: imjohnbo/issue-bot@v3
        id: issue
        with:
          labels: "release"
          title: "Release ${{ env.TAG }}"
          body: |
            ## Information
            Author: ${{ env.AUTHOR }}
            Release Date: ${{ env.DATE }}

            ## Changelog
            ${{ env.CHANGELOG }}
          token: ${{ env.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release branch
        run: |
          git checkout -b ${{ env.BRANCH }}
          git push -u origin ${{ env.BRANCH }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Deps
        run: |
          npm ci
          npx playwright install --with-deps chromium
      - name: Run Unit Tests
        run: npm test
      - name: Run e2e Tests
        run: npm run ci:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Build
        run: npm run build
      - name: Log tests and build to issue
        uses: actions/github-script@v6
        env:
          ISSUE_NUMBER: ${{ steps.issue.outputs.issue_number }}
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue: process.env.ISSUE_NUMBER,
              body: "Successfuly ran tests and build"
            })
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - name: Log Deployment 
        uses: actions/github-script@v6
        env:
          ISSUE_NUMBER: ${{ steps.issue.outputs.issue_number }}
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue: process.env.ISSUE_NUMBER,
              body: "Successfuly deployed"
            })

