name: Release-Process

on:
  push:
    tags:
      - "v*"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  create_issue:
    name: Create issue
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.x]

    runs-on: ${{ matrix.os }}

    outputs:
      unit_test_success: ${{ steps.unit_test.outcome == 'success' }}
      e2e_test_success: ${{ steps.e2e_test.outcome == 'success' }}

    steps:
      - name: Get the repo code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps chromium

      - name: "Tests: unit"
        id: unit_test
        run: |
          npm run test-unit-ci && echo "UNIT_TEST_RESULT='PASSED ✅'" >> $GITHUB_ENV || echo "UNIT_TEST_RESULT='FAILED 🚫'" >> $GITHUB_ENV
        continue-on-error: true

      - name: "Tests: e2e"
        id: e2e_test
        run: |
          npm run test-e2e-ci && echo "E2E_TEST_RESULT='PASSED ✅'" >> $GITHUB_ENV || echo "E2E_TEST_RESULT='FAILED 🚫'" >> $GITHUB_ENV
        continue-on-error: true

      - name: Upload Artifacts (unit tests)
        uses: actions/upload-artifact@v3
        with:
          name: Report (unit tests)
          path: test-report.html
          if-no-files-found: error

      - name: Upload Artifacts (e2e tests)
        uses: actions/upload-artifact@v3
        with:
          name: Report (e2e tests)
          path: ./playwright-report
          if-no-files-found: error

      - name: Save release version
        run: echo "RELEASE_VER=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Release Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const title = `Release ${process.env.RELEASE_VER}`
            let body = `Author: ${context.payload.sender.login}\n`
            body += `Date: ${new Date().toLocaleString()}\n`
            body += `Version: ${process.env.RELEASE_VER}\n\n`

            body += `Unit tests results: ${process.env.UNIT_TEST_RESULT}\n`
            body += `E2E tests results: ${process.env.E2E_TEST_RESULT}\n`
            body += `Test results: ${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${context.runId}`

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['RELEASE']
            })

  deploy:
    needs: create_issue
    if: needs.create_issue.outputs.unit_test_success && needs.create_issue.outputs.e2e_test_success
    uses: ./.github/workflows/static.yml
