name: Release-Process
on:
  push:
    branches:
      - master
    tags:
      - "v[0-9]+"

jobs:
  create_issue:
    name: Create changelog
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci

      - name: Check release version from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Release Issue
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const issueTitle = `Release ${process.env.RELEASE_VERSION}`
            let body = `Author: ${context.payload.sender.login}\n`
            body += `Date: ${new Date().toLocaleString()}\n`
            body += `Version: ${process.env.RELEASE_VERSION}\n\n`

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: body,
              labels: ['RELEASE']
            })
