name: Release-Process

on:
  push:
    tags:
      - "v*"

jobs:
  create_issue:
    name: Create issue
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Get the repo code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Check release version from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Release Issue
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const issueTitle = `Release ${process.env.RELEASE_VERSION}`
            let body = `Author: ${context.payload.sender.login}\n`
            body += `Date: ${new Date().toLocaleString()}\n`
            body += `Version: ${process.env.RELEASE_VERSION}\n\n`

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: body,
              labels: ['RELEASE']
            })
