name: Release

on:
  push:
    tags:
      - 'v[0-9]+'

jobs:
  release:

    permissions: write-all

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Generate Tag Report
        run: bash ./.github/scripts/generate_report.sh 
      - name: Create issue
        uses: imjohnbo/issue-bot@v3
        id: issue
        with:
          labels: "release"
          title: "Release ${{ env.TAG }}"
          body: |
            ## Information
            Author: ${{ env.AUTHOR }}
            Release Date: ${{ env.DATE }}

            ## Changelog
            ${{ env.CHANGELOG }}
          token: ${{ env.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release branch
        run: |
          git checkout -b ${{ env.BRANCH }}
          git push -u origin ${{ env.BRANCH }}

