name: Review changes
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Lint
        run: npm run lint
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Run tests
        run: npm run test:unit:ci
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Install playwright dependencies
        run: npx playwright install --with-deps chromium
      - name: Run tests
        run: npm run test:e2e:ci
