name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create-branch:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: release/${{ steps.vars.outputs.tag }}
      - uses: actions/checkout@v3
        with:
          ref: release/${{ steps.vars.outputs.tag }}
      - name: Get current package version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - run: echo ${{ steps.package-version.outputs.current-version}}
      - name: package-json-version
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          npm version ${{ steps.vars.outputs.tag }}
      - name: Commit version
        run: |
          git push
      - name: Release Changelog Builder
         uses: mikepenz/release-changelog-builder-action@v4.0.0-rc03
      - run: |
          git commit -m:"chore:add changelog"
          git push
