name: Test and Lint all commits on Pull Request

on: pull_request

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      
      - name: Get sourcecode
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install dependencies
        run: |
          npm ci
          npm i --save-dev eslint-config-react-app eslint
          npx playwright install --with-deps chromium
          
      - run: |
          for commit in $(git rev-list ${{ github.event.before}}..${{ github.sha}}); do
              echo $commit
              git checkout $commit
              npx eslint ./src
              npm test
              npm run e2e
          done
          
