name: test-github-actions
run-name: ${{ github.actor }} is running tests
on: [pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: nm

  unit-tests:
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: nm

      - name: Run unit tests
        run: npm run test-ci
      
        if: always()
      - uses: actions/upload-artifact@v2
        with:
          name: junit
          path: junit.xml
          retention-days: 30  

  e2e-tests:
    needs: setup
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: nm
             
      - name: Install playwright
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: npm run e2e-ci

        if: always()
      - uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30  
